"""add shop columns

Revision ID: dfde23adeb33
Revises: 60c6df430cbf
Create Date: 2026-05-30 12:11:16.439586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfde23adeb33'
down_revision = '60c6df430cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('unlocked_items', sa.String(length=500), nullable=False, server_default='ball_classic,jersey_fb,jersey_gs,decor_classic,glove_classic'))
        batch_op.add_column(sa.Column('equipped_ball', sa.String(length=50), nullable=False, server_default='ball_classic'))
        batch_op.add_column(sa.Column('equipped_jersey', sa.String(length=50), nullable=False, server_default='jersey_fb'))
        batch_op.add_column(sa.Column('equipped_decor', sa.String(length=50), nullable=False, server_default='decor_classic'))
        batch_op.add_column(sa.Column('equipped_glove', sa.String(length=50), nullable=False, server_default='glove_classic'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('equipped_glove')
        batch_op.drop_column('equipped_decor')
        batch_op.drop_column('equipped_jersey')
        batch_op.drop_column('equipped_ball')
        batch_op.drop_column('unlocked_items')
        batch_op.drop_column('coins')

    # ### end Alembic commands ###
